[global]
error_log = /dev/stderr
[www]
user = laravel
group = laravel
listen = 127.0.0.1:9000

pm = ondemand
pm.max_children = 20

pm.status_path = /fpm-status
ping.path = /fpm-ping

pm.process_idle_timeout = 10s;
pm.max_requests = 100
clear_env = no
catch_workers_output = yes
decorate_workers_output = no
